language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "devcenter-es"
    branches:
      - master
      - features.*
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -PGEN-RESOURCES
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -PGEN-RESOURCES