spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: true
debug: false
spring.messages.basename: messages/messages

server.uploadPath: C:\proyectos\sede\
verifirma.url: http://demo.gexflow.com:8080
verifirma.user: servicio.consulta.expedientes
verifirma.password: servicio.consulta.expedientes

sede:
  ws.tramites: http://demo.gexflow.com:8080/gexflowzk/ws/CatalogoTramites
  ws.admin: http://demo.gexflow.com:8080/gexflowzk/ws/WSAdminGexflowZK
  ws.pasarela: https://demo.gexflow.com:8443/pasarelaintegracion/ws/Autenticacion
  carpeta.ciudadana: https://demo.gexflow.com:8443/CarpetaCiudadana/{idEntidad}/VerMisTramites
  iniciar.tramite: https://demo.gexflow.com:8443/CarpetaCiudadana/IniciarTramiteConTicket?idEntidad={idEntidad}&id={idServicio}&idTicket={ticket}
  requisitos.tecnicos: https://demo.gexflow.com:8443/CarpetaCiudadana/requisitos.html
  conoce.tu.ayuntamiento: http://www.murcia.es/web/portal/institucional
  portal.transparencia: http://www.murcia.es/web/portal/transparencia-municipal
  url.descarga: http://demo.gexflow.com:8080/gexflowzk
  procedimiento:
    ocupacion.via.publica: 4
    instancia.general: 11
    quejas.sugerencias: 12
    empadronamiento: 101
    