spring.datasource.url: jdbc:postgresql://localhost/sede
spring.datasource.username: sede
spring.datasource.password: sede
server:
  port: 8081

spring.jpa.show-sql: true

server.basePathBack: http://localhost:8081
server.contextPath: /sede 
server.uploadPath: C:\proyectos\sede\
file.strKey: Bar12345Bar12345

spring:
  thymeleaf: 
    cache: false
    mode: HTML5
    enconding: UTF-8
    
spring.http.multipart.max-file-size: 100Mb
spring.http.multipart.max-request-size: 100Mb

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor: ERROR
logging.level.org.hibernate.type.EnumType: ERROR

# Uncomment the keys to enable captcha
google.recaptcha.key.site: 6LcXrUcUAAAAAL1kUs8PM_007ClcXBHkt5L_YgqZ
google.recaptcha.key.secret: 6LcXrUcUAAAAAGeDgCq_H1k7JQE0j2Ett4km0xwz

spring.mail.host: smtp.gmail.com
spring.mail.username: ######
spring.mail.password: ##########
spring.mail.port: 587
spring.mail.properties.mail.smtp.starttls.enable: true
