spring.datasource.url: jdbc:postgresql://localhost/sede
spring.datasource.username: sede
spring.datasource.password: sede
server:
  port: 8081

spring.jpa.show-sql: false
flyway.enabled: true


server.basePathBack: http://localhost:8081
server.contextPath: /sede 
server.uploadPath: C:\proyectos\sede\
file.strKey: Bar12345Bar12345

verifirma.url: http://localhost:9080
verifirma.user: servicio.consulta.expedientes
verifirma.password: servicio.consulta.expedientes


spring:
  thymeleaf: 
    cache: false
    mode: HTML
    enconding: UTF-8
    
spring.http.multipart.max-file-size: 100Mb
spring.http.multipart.max-request-size: 100Mb

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor: ERROR
logging.level.org.hibernate.type.EnumType: ERROR

# Uncomment the keys to enable captcha
google.recaptcha.key.site: 6LcXrUcUAAAAAL1kUs8PM_007ClcXBHkt5L_YgqZ
google.recaptcha.key.secret: 6LcXrUcUAAAAAGeDgCq_H1k7JQE0j2Ett4km0xwz

spring.data.rest.default-page-size: 10
spring.data.rest.max-page-size: 10

spring.mail.host: smtp.gmail.com
spring.mail.username: ######
spring.mail.password: ##########
spring.mail.port: 587
spring.mail.properties.mail.smtp.starttls.enable: true

server.uploadPath: C:\proyectos\sede\
verifirma.url: http://localhost:9080
verifirma.user: servicio.consulta.expedientes
verifirma.password: servicio.consulta.expedientes

sede:
  entidad: 0
  ws.tramites: http://localhost:9080/gexflowzk/ws/CatalogoTramites
  ws.admin: http://localhost:9080/gexflowzk/ws/WSAdminGexflowZK
  ws.pasarela: 
    url: https://localhost:9443/pasarelaintegracion/ws/Autenticacion
    usuario: teralco
    password: 481a5fe58d2ace784783158c4b8be6dd
  carpeta.ciudadana: https://localhost:9443/CarpetaCiudadana/${sede.entidad}/VerMisTramites
  iniciar.tramite: https://localhost:9443/CarpetaCiudadana/IniciarTramiteConTicket?idEntidad=${sede.entidad}&id={idServicio}&idTicket={ticket}
  requisitos.tecnicos: https://localhost:9443/CarpetaCiudadana/requisitos.html
  conoce.tu.ayuntamiento: http://www.ibi.es/seccion.asp?idseccion=11454
  portal.transparencia: https://ibi.transparencialocal.gob.es/
  url.descarga: http://localhost:9080/gexflowzk
  procedimiento:
    destacado.uno: 101
    destacado.dos: 109
    destacado.tres: 106
    destacado.cuatro: 100
    instancia.general: 100
    quejas.sugerencias: 102


