spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: true
debug: false
spring.messages.basename: messages/messages

server.uploadPath: C:\proyectos\sede\
verifirma.url: http://demo.gexflow.com:8080
verifirma.user: servicio.consulta.expedientes
verifirma.password: servicio.consulta.expedientes
