spring.datasource.url: jdbc:postgresql://localhost/sede
spring.datasource.username: sede
spring.datasource.password: sede
server:
  port: 8081

spring.jpa.show-sql: true

server.basePathBack: http://localhost:8081
server.contextPath: /sede 
server.uploadPath: C://proyectos//sede//

spring:
  thymeleaf: 
    cache: false
    mode: HTML5
    enconding: UTF-8
    

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor: ERROR
logging.level.org.hibernate.type.EnumType: ERROR


